version: '3.8'
services:
  db:
    image: mariadb:10
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - mysql_root_password
      - mysql_user_password
      - mysql_database  # Nouveau secret pour la base de données
      - mysql_user  # Nouveau secret pour l'utilisateur
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE_FILE: /run/secrets/mysql_database  # Secret pour le nom de la DB
      MYSQL_USER_FILE: /run/secrets/mysql_user  # Secret pour le nom de l'utilisateur
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
    networks:
      - backend
    ports:
      - "3306:3306"  # Ouvrir le port 3306 pour MySQL

  wordpress-php-fpm:
    image: wordpress:php7.4-fpm
    deploy:
      replicas: 2
      restart_policy:
        condition: any
    volumes:
      - wordpress_data:/var/www/html
      - nfs_data:/var/www/nfs  # Ajout du volume NFS
    networks:
      - frontend
      - backend
    ports:
      - "8081:80"

  nginx:
    image: nginx:alpine
    deploy:
      replicas: 2
      restart_policy:
        condition: any
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - wordpress_data:/var/www/html
      - nfs_data:/var/www/nfs  # Ajout du volume NFS
      - ./log/nginx:/var/log/nginx
    ports:
      - "8080:80"  # Port 80 exposé à la machine locale
    networks:
      - frontend
      - backend

volumes:
  db_data:
  wordpress_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=172.26.1.5,nolock,soft,rw"
      device: ":/var/nfs_share/srv11"
  nfs_data:  # Ajout du volume NFS
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=172.26.1.5,nolock,soft,rw"
      device: ":/var/nfs_share/srv11"

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  mysql_user_password:
    file: ./secrets/mysql_user_password.txt
  mysql_database:  # Nouveau secret pour la base de données
    file: ./secrets/mysql_database.txt
  mysql_user:  # Nouveau secret pour l'utilisateur MySQL
    file: ./secrets/mysql_user.txt

networks:
  frontend:
  backend:
