version: '3.8' 
services:
  db:
    image: mariadb:10
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager  # Assurez-vous que la base de données est sur le nœud manager
    volumes:
      - db_data:/var/lib/mysql  # Volume persistant pour la base de données
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "Db_swarm"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
    networks:
      - backend

  wordpress:
    image: wordpress:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: any
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: "root"
      WORDPRESS_DB_PASSWORD: "root"
      WORDPRESS_DB_NAME: "Db_swarm"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - frontend
      - backend
    ports:
      - "${PORT}:80"  

  nginx:
    image: nginx:alpine
    deploy:
      replicas: 2
      restart_policy:
        condition: any
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx:/var/log/nginx
    networks:
      - frontend
    ports:
      - "80:80"

volumes:
  db_data:
  wordpress_data:

networks:
  frontend:
  backend:
