version: '3.8'
services:
  db:
    image: mariadb:10
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "db_swarm"
      MYSQL_USER: "swarm"
      MYSQL_PASSWORD: "root"
    networks:
      - backend

  wordpress-php-fpm:
    image: wordpress:php7.4-fpm
    deploy:
      replicas: 2
      restart_policy:
        condition: any
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - frontend
      - backend

  nginx:
    image: nginx:alpine
    deploy:
      replicas: 2
      restart_policy:
        condition: any
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - wordpress_data:/var/www/html
      - ./log/nginx:/var/log/nginx
    ports:
      - "80:80" 
    networks:
      - frontend

volumes:
  db_data:
  wordpress_data:

networks:
  frontend:
  backend:
